apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: dev-svc-{{name}}-frontend
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: dev-{{name}}-frontend
